### PR TITLE
Setting the textContent of a document fragment to an empty string should remove all its content

### PR DESCRIPTION
**Pull request by vlukashov**
Fix the `textContent` issue webcomponents/webcomponentsjs#754:

The spec [says](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#Description) that setting the `textContent` of a document fragment to an empty string should remove all its content:

```javascript
let fragment = document.createDocumentFragment();
fragment.appendChild( document.createElement( 'div' ) );
console.log(fragment.childElementCount); // prints 1

fragment.textContent = '';
console.log(fragment.childElementCount); // prints 0
```

When the Shady DOM v1 polyfill is active that's no longer the case:
```javascript
let fragment = document.createDocumentFragment();
fragment.appendChild( document.createElement( 'div' ) );
console.log(fragment.childElementCount); // prints 1

fragment.textContent = '';
console.log(fragment.childElementCount); // still prints 1
```

More details and a demo [here](https://github.com/vlukashov/shady-dom-set-text-content).

### CODE REVIEW

**Comment by sorvell** [comment]
Thanks for the PR. This was merged into: https://github.com/webcomponents/shadydom/pull/164.

**Comment by bwolff** [comment]
@sorvell are you sure that this fixed was actually merged into #164 ?? From the diff in #164 I can't neither see the actual fix nor the added unit test that was initially contributed by this PR.

Also, using the latest version of webcomponentjs 1.0.4, the issue still persists. This fix is quite critical, since it basically breaks many jQuery based plugins that would otherwise work fine.

Could you please double check if the change was actually merged and not overridden by other changes to the same chunks? Thank you.

Can somebody configmr that it was not fixed in the latest version of webcomponents 1.0.4 and shadydom 1.0.2? Just to avoid the "is it just me" effect.

**Comment by azakus** [comment]
No, it clearly wasn't merged in, but I think what @sorvell meant to say is that #164 was supposed to solve this issue in a different way. I'm going to verify whether that is the case.

**Comment by azakus** [comment]
Nope, those tests still fail. Reopening.

**Comment by azakus** [comment]
@bwolff should be fixed with https://github.com/webcomponents/shadydom/pull/172

**Pull request closed without merging**
