### PR TITLE
Export getElementById

### PR DESCRIPTION
**Pull request by rslawik**
The polyfilled version of `document.getElementById` scans the entire DOM subtree. Doing it multiple times on the critical path adds significant overhead and causes unnecessary GC.
The native `getElementById` can be used if the searched element has a **globally** unique id.

GWT (_Google Web Toolkit_) framework performs series of such lookups when it constructs widgets. The searches are for elements with autogenerated ids.

### CODE REVIEW

**Comment by rslawik** [comment]
Updated the pull request.

**Comment by bicknellr** [comment]
Hi, a few of us just had a meeting with @rslawik and it sounds like this is fairly important. Would a code owner for this repo mind reviewing?
ping @azakus, @sorvell

**Comment by TimvdLippe** [comment]
LGTM'd by @azakus as wel. Could you rebase and regenerate the minified files? Then we can merge.

**Comment by rslawik** [comment]
Done.

**Pull request merged**
